#!/usr/bin/env bash
#Configures an Ubuntu server with some requirements
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8

# Configure localhost resolution
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null

# Configure facebook.com resolution
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
