#!/usr/bin/env bash
# Creates and RAS key pair
# private key named school, number of bits in the created key is 4096
# created key protected by passphrase betty

ssh-keygen -t rsa -N betty -f school -b 4096
